config/routes.rb
Rails.application.routes.draw do
  resources :stupids
  #get 'homes/index'
  resources :blogs
  resources :interview_questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/inter_view_question.rb
class InterViewQuestion < ApplicationRecord
end

app/models/reminder.rb
class Reminder < ApplicationRecord
end

app/models/stupid.rb
class Stupid < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @blogs = Blog.all 
  end 

  def new
    @blog = Blog.new
  end 

  def create
    #@blog = Blog.new(params[:blog])
    #params.require(:profile).permit(:stage_name, :category, :user_id, :profile_type, :location, :username)
    @blog = Blog.new(params.require(:blog).permit(:title, :sub_title, :description))
    if @blog.save
      redirect_to blogs_path
    else
      redirect_to blogs_path
    end
    #render plain: params[:article].inspect
  end

  def show
  end

  def edit
  end 

  def update
  end 

  def destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/interview_questions_controller.rb
class InterviewQuestionsController < ApplicationController

  def index
  end 

  def new
  end 

  def create
  end

  def show
  end

  def edit
  end 

  def update
  end 

  def destroy
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
end

app/controllers/stupids_controller.rb
class StupidsController < ApplicationController
  before_action :set_stupid, only: [:show, :edit, :update, :destroy]

  # GET /stupids
  # GET /stupids.json
  def index
    @stupids = Stupid.all
  end

  # GET /stupids/1
  # GET /stupids/1.json
  def show
  end

  # GET /stupids/new
  def new
    @stupid = Stupid.new
  end

  # GET /stupids/1/edit
  def edit
  end

  # POST /stupids
  # POST /stupids.json
  def create
    @stupid = Stupid.new(stupid_params)

    respond_to do |format|
      if @stupid.save
        format.html { redirect_to @stupid, notice: 'Stupid was successfully created.' }
        format.json { render :show, status: :created, location: @stupid }
      else
        format.html { render :new }
        format.json { render json: @stupid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stupids/1
  # PATCH/PUT /stupids/1.json
  def update
    respond_to do |format|
      if @stupid.update(stupid_params)
        format.html { redirect_to @stupid, notice: 'Stupid was successfully updated.' }
        format.json { render :show, status: :ok, location: @stupid }
      else
        format.html { render :edit }
        format.json { render json: @stupid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stupids/1
  # DELETE /stupids/1.json
  def destroy
    @stupid.destroy
    respond_to do |format|
      format.html { redirect_to stupids_url, notice: 'Stupid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stupid
      @stupid = Stupid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stupid_params
      params.require(:stupid).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/interview_questions_helper.rb
module InterviewQuestionsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/stupids_helper.rb
module StupidsHelper
end

app/views/blogs/index.html.erb
<p> Blog details </p>
<%= link_to "Create Blog", new_blog_path()%>
<table class=" table table-striped" data-sort-name="name" data-sort-order="desc">
  <thead>
    <tr>
      <th data-field="name" data-sortable="true">title</th>
      <th data-field="age" data-sortable="true">subtitle</th>
      <th data-field="age" data-sortable="true">Details</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.sub_title %></td>
        <td><%= link_to "show Details", blog_path(blog) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<%= bootstrap_form_for(@blog) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :sub_title %>
  <%= f.text_area :description%>
  <%= f.submit "Create" %>
<% end %>

app/views/homes/index.html.erb
<%= link_to "go to blogs", blogs_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BhimaBlog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BhimaBlog</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stupids/_form.html.erb
<%= form_for(stupid) do |f| %>
  <% if stupid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stupid.errors.count, "error") %> prohibited this stupid from being saved:</h2>

      <ul>
      <% stupid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stupids/edit.html.erb
<h1>Editing Stupid</h1>

<%= render 'form', stupid: @stupid %>

<%= link_to 'Show', @stupid %> |
<%= link_to 'Back', stupids_path %>

app/views/stupids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stupids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stupids.each do |stupid| %>
      <tr>
        <td><%= stupid.name %></td>
        <td><%= link_to 'Show', stupid %></td>
        <td><%= link_to 'Edit', edit_stupid_path(stupid) %></td>
        <td><%= link_to 'Destroy', stupid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stupid', new_stupid_path %>

app/views/stupids/new.html.erb
<h1>New Stupid</h1>

<%= render 'form', stupid: @stupid %>

<%= link_to 'Back', stupids_path %>

app/views/stupids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stupid.name %>
</p>

<%= link_to 'Edit', edit_stupid_path(@stupid) %> |
<%= link_to 'Back', stupids_path %>